### Parte 3 – Cruce por ubigeo y análisis

#### Paso 1
Crear el archivo datos/ubigeos.csv con las columnas ubigeo y departamento

In [2]:
import pandas as pd
import os

ubigeos = pd.DataFrame({
    "ubigeo": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
               "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
               "21", "22", "23", "24", "25"],
    "departamento": ["Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho",
                     "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco",
                     "Ica", "Junín", "La Libertad", "Lambayeque", "Lima",
                     "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura",
                     "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"]
})

os.makedirs("datos", exist_ok=True)

ubigeos.to_csv("datos/ubigeos.csv", index=False, encoding="utf-8-sig")

ubigeos

   ubigeo   departamento
0      01       Amazonas
1      02         Áncash
2      03       Apurímac
3      04       Arequipa
4      05       Ayacucho
5      06      Cajamarca
6      07         Callao
7      08          Cusco
8      09   Huancavelica
9      10        Huánuco
10     11            Ica
11     12          Junín
12     13    La Libertad
13     14     Lambayeque
14     15           Lima
15     16         Loreto
16     17  Madre de Dios
17     18       Moquegua
18     19          Pasco
19     20          Piura
20     21           Puno
21     22     San Martín
22     23          Tacna
23     24         Tumbes
24     25        Ucayali

#### Paso 2
Leer archivo normal y otra con *dtype={"ubigeo": str}*. Mostrar la diferencia y explicar la importancia

In [3]:
# Lectura normal
ubigeo_0= pd.read_csv("datos/ubigeos.csv")
print("Lectura normal:")
print(ubigeo_0.head())
print()
print(ubigeo_0.dtypes)

# Lectura con dtype
ubigeo = pd.read_csv("datos/ubigeos.csv", dtype={"ubigeo": str})
print("\nLectura con dtype:")
print(ubigeo.head())
print()
print(ubigeo.dtypes)

Lectura normal:
   ubigeo departamento
0       1     Amazonas
1       2       Áncash
2       3     Apurímac
3       4     Arequipa
4       5     Ayacucho

ubigeo          int64
departamento      str
dtype: object

Lectura con dtype:
  ubigeo departamento
0     01     Amazonas
1     02       Áncash
2     03     Apurímac
3     04     Arequipa
4     05     Ayacucho

ubigeo          str
departamento    str
dtype: object

Ambas lecturas muestran una diferencia en la variable ubigeo. En la lectura normal, se importa como número entero y se borra el 0 que se había colocado al inicio en los casos que tenían 1 dígito. Mientras que, en la lectura con dtype={"ubigeo": str}, como se establece en específico que se considere a la variable "ubigeo" como string, se mantiene la variable como string y no se modifica. 

**Importancia:** Identificar esta diferencia es importante ya que permite visualizar la relevancia de especificar el tipo de variable al momento de importarlo, en especial en casos donde la variable podría calificar como diferentes tipos y no esté muy claro cómo se quisiera que se considere, como el caso de la variable "ubigeo". Además, si luego se quiere unir una base con otra a través de esa variable es importante que estén en el mismo formato para que no se presenten inconvenientes.

### Paso 3
Agregar ubigeo a decretos_por_departamento.csv y a lluvias_por_departamento.csv

In [9]:
# Bases originales
decretos= pd.read_csv("datos/decretos_por_departamento.csv")
lluvias= pd.read_csv("datos/lluvias_por_departamento.csv")

display(decretos.head())
display(lluvias.head())

  departamento  declaratorias  prorrogas
0     Amazonas              4          2
1       Áncash              5          5
2     Apurímac              7          4
3     Arequipa              7          6
4     Ayacucho              7          5

,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte
0,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19
1,Junín,Huancayo,-12.06866,-75.21027,1276.9,11
2,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15
3,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3
4,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9

In [11]:
# Agregar ubigeo por nombre de departamento
decretos_ubi = decretos.merge(ubigeo, on="departamento", how="left")
lluvias_ubi = lluvias.merge(ubigeo, on="departamento", how="left")

display(decretos_ubi.head())
display(lluvias_ubi.head())

  departamento  declaratorias  prorrogas ubigeo
0     Amazonas              4          2     01
1       Áncash              5          5     02
2     Apurímac              7          4     03
3     Arequipa              7          6     04
4     Ayacucho              7          5     05

,departamento,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte,ubigeo
0,Loreto,Iquitos,-3.74814,-73.25290,1361.8,19,16
1,Junín,Huancayo,-12.06866,-75.21027,1276.9,11,12
2,Madre de Dios,Puerto Maldonado,-12.58946,-69.19948,1149.5,15,17
3,Áncash,Huaraz,-9.52614,-77.52869,1058.3,3,02
4,Ucayali,Pucallpa,-8.37915,-74.55387,887.4,9,25

### Paso 4
Mostrar los departamentos que no encontraron su ubigeo y corregir hasta que no quede ninguno

In [12]:
# Archivo decretos por departamento
print("Filas",len(decretos),"->",len(decretos_ubi))
print("No cruzó: ",decretos_ubi["ubigeo"].isna().sum())
print(decretos_ubi[decretos_ubi["ubigeo"].isna()].head()) #vacío, todos cruzaron

Filas 25 -> 25
No cruzó:  0
Empty DataFrame
Columns: [departamento, declaratorias, prorrogas, ubigeo]
Index: []

In [13]:
# Archivo lluvias por departamento
print("Filas",len(lluvias),"->",len(lluvias_ubi))
print("No cruzó: ",lluvias_ubi["ubigeo"].isna().sum())
print(lluvias_ubi[lluvias_ubi["ubigeo"].isna()].head()) #vacío, todos cruzaron

Filas 25 -> 25
No cruzó:  0
Empty DataFrame
Columns: [departamento, capital, latitud, longitud, lluvia_total_mm, dias_lluvia_fuerte, ubigeo]
Index: []

En ambas bases lograron cruzarse todas las filas con la base ubigeo